# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [25]:
#Type your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
import joblib

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [26]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
# ___ = pd_read_csv("___.csv")
data_clustering = pd.read_csv('data_clustering.csv')
data_clustering_inverse = pd.read_csv('data_clustering_inverse.csv')

In [27]:
# Tampilkan 5 baris pertama dengan function head.
print("Tampilkan 5 baris pertama pada dataset clustering :")
print(data_clustering.head())

print("Tampilkan 5 baris pertama pada dataset clustering_inverse :")
print(data_clustering_inverse.head())

Tampilkan 5 baris pertama pada dataset clustering :
   TransactionAmount  TransactionDate  TransactionType  Location  Channel  \
0           0.007207              680                1        36        0   
1           0.195940             1178                1        15        0   
2           0.065680             1262                1        23        2   
3           0.096016              818                1        33        2   
4           0.047888              635                1        28        0   

   CustomerAge  CustomerOccupation  TransactionDuration  LoginAttempts  \
0     0.838710                   0             0.244828            0.0   
1     0.806452                   0             0.451724            0.0   
2     0.016129                   3             0.158621            0.0   
3     0.129032                   3             0.051724            0.0   
4     0.000000                   3             0.558621            0.0   

   AccountBalance  PreviousTransactionDa

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [28]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
X = data_clustering.drop('Target', axis=1)
y = data_clustering['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

categorical_cols = X_train.select_dtypes(include=['object']).columns

X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='left', axis=1, fill_value=0)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [29]:
# Buatlah model klasifikasi menggunakan Decision Tree
model = DecisionTreeClassifier().fit(X_train_encoded, y_train_encoded)
print("Model Training selesai")

Model Training selesai


In [30]:
# Menyimpan Model
# import joblib
# joblib.dump(model, 'decision_tree_model.h5')
joblib.dump(model, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [31]:
# Melatih model menggunakan algoritma klasifikasi selain Decision Tree.
knn = KNeighborsClassifier().fit(X_train_encoded, y_train_encoded)
rf = RandomForestClassifier().fit(X_train_encoded, y_train_encoded)
svm = SVC().fit(X_train_encoded, y_train_encoded)
nb = GaussianNB().fit(X_train_encoded, y_train_encoded)

print("Model Training selesai")

Model Training selesai


In [32]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    results = {
        'Confusion Matrix': cm,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred, average='weighted'),
        'F1-Score': f1_score(y_test, y_pred, average='weighted')
    }
    return results

# Mengevaluasi setiap model dan mengumpulkan hasilnya
model_results = {
    'Decision Tree': evaluate_model(model, X_test_encoded, y_test_encoded),
    'K-Nearest Neighbors': evaluate_model(knn, X_test_encoded, y_test_encoded),
    'Random Forest': evaluate_model(rf, X_test_encoded, y_test_encoded),
    'Support Vector Machine (SVM)': evaluate_model(svm, X_test_encoded, y_test_encoded),
    'Naive Bayes (NB)': evaluate_model(nb, X_test_encoded, y_test_encoded)
}

rows = []
for model_name, metrics in model_results.items():
    rows.append({
        'Model': model_name,
        'Accuracy': metrics['Accuracy'],
        'Precision': metrics['Precision'],
        'Recall': metrics['Recall'],
        'F1-Score': metrics['F1-Score']
    })

summary_df = pd.DataFrame(rows)

print(summary_df)

                          Model  Accuracy  Precision    Recall  F1-Score
0                 Decision Tree  1.000000   1.000000  1.000000  1.000000
1           K-Nearest Neighbors  0.988539   0.988606  0.988539  0.988540
2                 Random Forest  1.000000   1.000000  1.000000  1.000000
3  Support Vector Machine (SVM)  1.000000   1.000000  1.000000  1.000000
4              Naive Bayes (NB)  0.962751   0.963347  0.962751  0.962762


In [33]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
# joblib.dump(___, 'explore_<Nama Algoritma>_classification.h5')
joblib.dump(knn, 'explore_KNN_classification.h5')
joblib.dump(rf, 'explore_RF_classification.h5')
joblib.dump(svm, 'explore_SVM_classification.h5')
joblib.dump(nb, 'explore_NB_classification.h5')

['explore_NB_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [34]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.
param_grid = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy']
}

grid_search = GridSearchCV(estimator=DecisionTreeClassifier(), param_grid=param_grid, cv=5, scoring='accuracy')

grid_search.fit(X_train_encoded, y_train_encoded)

model_dt = grid_search.best_estimator_

print("Best Hyperparameters:", grid_search.best_params_)

dt_tuned_results = evaluate_model(model_dt, X_test_encoded, y_test_encoded)

Best Hyperparameters: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}


In [35]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
print("\nEvaluasi Model Decision Tree (Tuned):")
print(f"Accuracy: {dt_tuned_results['Accuracy']:.4f}")
print(f"Precision: {dt_tuned_results['Precision']:.4f}")
print(f"Recall: {dt_tuned_results['Recall']:.4f}")
print(f"F1-Score: {dt_tuned_results['F1-Score']:.4f}")
print("Confusion Matrix:\n", dt_tuned_results['Confusion Matrix'])


Evaluasi Model Decision Tree (Tuned):
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
Confusion Matrix:
 [[82  0  0  0]
 [ 0 83  0  0]
 [ 0  0 98  0]
 [ 0  0  0 86]]


In [36]:
# Menyimpan Model hasil tuning
# import joblib
# joblib.dump(__, 'tuning_classification.h5')
joblib.dump(model_dt, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code